apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-llfqzlgy
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-llfqzlgy:e8f99c5cfc9776bbd1cdaf538d418ba1e7c18811@sha256:b533e88c17a4b6353d371acd014b69e132bc92176ecad21f9a1a296a1e69ad77
        name: container-image  
